version: '3.5'

services:

  my-mysql:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my-mysql
    image: my-mysql
    ports:
      - "3306:3306"
    volumes:
      - database:/var/lib/mysql
    restart: always
    security_opt:
      - seccomp:unconfined
    command: ['--max_connections=1000']

  java-spring:
    depends_on:
      - my-mysql
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: java-spring
    image: java-spring
    ports:
      - "8083:8083"
    restart: always

  nginx-react:
    image: nginx-react
    container_name: nginx-react
    restart: always
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "80:80"

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - 9090:9090
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    depends_on:
      - cadvisor

  cadvisor:
    image: google/cadvisor:latest
    container_name: cadvisor
    ports:
      - 8080:8080
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro

  grafana:
    image: grafana/grafana:3.0.0-beta7
    environment:
        - GF_SECURITY_ADMIN_PASSWORD=pass
    depends_on:
        - prometheus
    ports:
        - "3000:3000"
    volumes:
        - grafana_data:/var/lib/grafana

volumes:
  database:
  grafana_data:
  prometheus_data: