version: '3.5'

services:

  mysql-master:
    build:
      context: ./mysql-cluster/master
      dockerfile: Dockerfile
    container_name: mysql-master
    expose:
      - "3306"
    ports:
      - "4406:3306"
    security_opt:
      - seccomp:unconfined
    volumes:
      - mysql-master:/var/lib/mysql/
      - ./mysql-cluster/master:/etc/mysql/conf.d/
    restart: always

  mysql-slave:
    build:
      context: ./mysql-cluster/slave
      dockerfile: Dockerfile
    container_name: mysql-slave
    expose:
      - "3306"
    ports:
      - "4407:3306"
    security_opt:
      - seccomp:unconfined
    volumes:
      - mysql-slave:/var/lib/mysql/
      - ./mysql-cluster/slave:/etc/mysql/conf.d/
    restart: always
    depends_on:
      - mysql-master

  java-spring:
    depends_on:
      - mysql-master
      - mysql-slave
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: java-spring
    image: java-spring
    ports:
      - "8083:8083"
    restart: always

  nginx-react:
    image: nginx-react
    container_name: nginx-react
    restart: always
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "80:80"

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - 9090:9090
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    depends_on:
      - cadvisor

  cadvisor:
    image: google/cadvisor:latest
    container_name: cadvisor
    ports:
      - 8080:8080
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro

  grafana:
    image: grafana/grafana:3.0.0-beta7
    container_name: grafana
    environment:
        - GF_SECURITY_ADMIN_PASSWORD=pass
    depends_on:
        - prometheus
    ports:
        - "3000:3000"
    volumes:
        - grafana_data:/var/lib/grafana

volumes:
  database:
  grafana_data:
  prometheus_data:
  mysql-master:
  mysql-slave: